import {
  bannerProduct1,
  bannerProduct2,
  bannerProduct3,
  bannerProduct4,
  catProduct1,
  catProduct2,
  catProduct3,
} from "@/constant";

export const products = [
  {
    title: "পাইকারি পণ্যের সমাহার",
    buttonText: "Coming Soon",
    image: bannerProduct1,
    link: "#",
  },
  {
    title: "এক ক্লিকে ভিজিট",
    buttonText: "Coming Soon",
    image: bannerProduct2,
    link: "#",
  },
  {
    title: "গ্রোসারিস পণ্যের সমাহার",
    buttonText: "Coming Soon",
    image: bannerProduct3,
    link: "#",
  },
  {
    title: "শিপিং সার্ভিস নিতে ভিজিট",
    buttonText: "Coming Soon",
    image: bannerProduct4,
    link: "#",
  },
];

export const allCategoriesProducts = [
  {
    id: 1,
    categoryId: 1,
    title: "Postage ~ Day Single U 99 Satchel",
    price: 229,
    image: catProduct1,
  },
  {
    id: 2,
    categoryId: 1,
    title: "Woven Straw Bag Women's Large",
    price: 338,
    image: catProduct2,
  },
  {
    id: 3,
    categoryId: 1,
    title: "Portable large capacity handmade s",
    price: 763,
    image: catProduct3,
  },
  {
    id: 4,
    categoryId: 1,
    title: "High-End Small Bag for Women Su",
    price: 780,
    image: catProduct1,
  },
  {
    id: 5,
    categoryId: 1,
    title: "Kou’s Spring New Laurel Stray Bag",
    price: 2875,
    image: catProduct2,
  },
  {
    id: 6,
    categoryId: 1,
    title: "C home city33 tote bag original hig",
    price: 3376,
    image: catProduct3,
  },
  {
    id: 7,
    categoryId: 1,
    title: "Postage ~ Day Single U 99 Satchel",
    price: 229,
    image: catProduct1,
  },
  {
    id: 8,
    categoryId: 1,
    title: "Woven Straw Bag Women's Large",
    price: 338,
    image: catProduct2,
  },
  {
    id: 9,
    categoryId: 1,
    title: "Portable large capacity handmade s",
    price: 763,
    image: catProduct3,
  },
  {
    id: 10,
    categoryId: 1,
    title: "High-End Small Bag for Women Su",
    price: 780,
    image: catProduct1,
  },
  {
    id: 11,
    categoryId: 1,
    title: "Kou’s Spring New Laurel Stray Bag",
    price: 2875,
    image: catProduct2,
  },
  {
    id: 12,
    categoryId: 1,
    title: "C home city33 tote bag original hig",
    price: 3376,
    image: catProduct3,
  },
  {
    id: 13,
    categoryId: 1,
    title: "Casual Large Capacity Sho",
    price: 654,
    image: catProduct1,
  },
  {
    id: 14,
    categoryId: 2,
    title: "Elegant Crystal Necklace",
    price: 1250,
    image: catProduct2,
  },
  {
    id: 15,
    categoryId: 3,
    title: "Men's Casual Leather Shoes",
    price: 1890,
    image: catProduct3,
  },
  {
    id: 16,
    categoryId: 4,
    title: "Matte Lipstick Set - 5 Shades",
    price: 720,
    image: catProduct1,
  },
  {
    id: 17,
    categoryId: 5,
    title: "Slim Fit Cotton Shirt",
    price: 990,
    image: catProduct1,
  },
  {
    id: 18,
    categoryId: 6,
    title: "Women's Summer Dress",
    price: 1580,
    image: catProduct2,
  },
  {
    id: 19,
    categoryId: 7,
    title: "Baby Soft Blanket Set",
    price: 650,
    image: catProduct3,
  },
  {
    id: 20,
    categoryId: 8,
    title: "UV-Protected Sunglasses",
    price: 1150,
    image: catProduct1,
  },
  {
    id: 21,
    categoryId: 9,
    title: "Magnetic Charging Cable",
    price: 350,
    image: catProduct2,
  },
  {
    id: 22,
    categoryId: 10,
    title: "Minimalist Analog Watch",
    price: 2250,
    image: catProduct3,
  },
];
